url: https://formulatingamess.github.io
baseurl: 

# Site settings
title: formulatingamess.eu
email: admin@formulatingamess.eu
description: ""

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: CC9900
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: V. Kabir Veitas
  pic: 1
  position: Lead Scientist
  company: 
    title: The Global Brain Institute
    url: http://www.globalbraininstitute.org
  social:
    - title: twitter
      url: https://twitter.com/vveitas
    - title: linkedin
      url: https://be.linkedin.com/pub/viktoras-veitas/3/119/a82

- name: Jon Echanove
  pic: 2
  position: Strategic Process Facilitator
  company: 
    title: Positive Development
    url: http://www.positivedevelopment.be
  social:
    - title: twitter
      url: https://twitter.com/jonechanove
    - title: linkedin
      url: http://t.co/zHiE5SaWFH

- name: Rasa Morkunaite
  pic: 3
  position: Partnership Manager
  company: 
    title: Economic Research Centre
    url: http://www.erc.lt
  social:
    - title: linkedin
      url: https://www.linkedin.com/pub/rasa-morkunaite/0/252/242

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url:

# Postal address (add as many lines as necessary)
address:
  - line: Avenue General de Longueville 1
  - line: Woluwe-Saint-Pierre, 1150, Brussels

# Build settings
markdown: kramdown
permalink: pretty
encoding: utf-8

